### ISSUE TITLE
Consider changing the name

### ISSUE THREAD

**Issue by RA-Kooi** [taibangle/awesome-china#5]
"Awesome China", however tongue in cheek, can be seen as coming out in support of China.
Maybe "Awesome Hong Kong" instead? Or "Horrible China"?

I think having Hong Kong in the name will help with discoverability of your repo.

**Comment by MeiWithHongKong** [comment]
Sorry the name won't be changed.

The name of the org, *taibangle*, is a reference to Mei's '哦, 太棒了！' (meaning woah, awesome!) voice line.
As for the repo name, *awesome-china*; the software community use 'awesome-x' to curate information about a specific topic, in this case China. (I'm sure you already know this, but I expect this issue will be seen by non-developers as well.)

I also believe the 'awesome-china' name will increase the chance that the content will be seen by Chinese people, which is one of the primary goals.

---

That being said, I'm fully supportive of people forking the repo, or copying whichever content they like to their own repos. I also found a few of the Wall of Shame entries from this great repo: https://github.com/caffeine-overload/bandinchina.
I don't agree with quite a few of the directions caffeine-overload/bandinchina have taken, such as the unnecessary 'date added' column, the decision to write content for the website rather than the repo, among a few other things. This is also why I wrote my own Wall of Shame list instead of linking to theirs. I'm sure there are also many who disagree with some of the directions I have taken, such as the repo name or the decision to focus on multiple topics rather than a single topic, in which case I hope they create their own project (and if they do, then they are welcome to promote it in the issues of this repo).

We are currently in a fortunate situation where GitHub is too valuable for the Chinese government to block, while at the same time GitHub/Microsoft is one of the few companies that doesn't censor its users. So far GitHub have only complied with 4 censorship requests by the Chinese government: https://github.com/github/gov-takedowns/tree/master/China, and in most cases, then they didn't take down the repo/issue, but they simply geo-blocked it for Chinese users, e.g. https://github.com/programthink/zhao/issues/38.
However, there is of course a risk that this repo (as well as other repos that are critical of the Chinese government) will be censored in the future, and it's therefore a good idea to spread the information across as many repos as possible. Doing so would also make it much more difficult for the Chinese government to prevent the information from being shared among the Chinese people.

**Comment by RA-Kooi** [comment]
> I also believe the 'awesome-china' name will increase the chance that the content will be seen by Chinese people, which is one of the primary goals.

I see, I wasn't aware of that. I thought you wanted this to be seen by western people, and educate them (more) on the matter.

Thank you for the thorough explanation though, I didn't expect such a detailed explanation.  
I'm not sure if you the gist of this information elsewhere in the repo, but I feel you definitely should.

And I agree with you that it's good to have many repos, it's the be like water tactic I saw some other protesters mention on Twitter, the harder to silence this information the better. I'm not really sure how I can help with that myself though, as I've only started learning about this recently, but do let me know if there's any way how I can support Hong Kong from here in the Netherlands.
