### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by seamounts** [taibangle/awesome-china#7]
你列的那些东西我们都知道，包括文化大革命等高中历史就专门有讲，也说了是不对的。里面好多东西你所知道的都是不全面的，每次看你们就罗列这些事情。而且有些都已经过去好久了。。。现在相比以前已经进步好多了。没必要每次抓住这些来攻击。

**Comment by NicoleTYF** [comment]
Hey thank you for spending time and effort reading the whole project before commenting! 

First, I think the creator's intention is to exchange knowledge, not triggering you to debate. If realness is your concern, you can choose to watch historical documentaries made in 1989. 
https://www.youtube.com/watch?v=QB9s5kSVj4Q

Second, It is okay if you have the statistics of what the 14 millions of Chinese people know or don't know. Your said your have heard of those in high school, but normally in some countries they won't teach the dark history of their country . So forgive your high school teachers being unable to teach the details of the sensitive content in 文化大革命 etc.. 

Right comes with responsibility, if you love your country, it is your responsibility to know the history. You can see these as an exchange of ideas as a reader instead of debating whether it is true or not.

**Comment by NjinN** [comment]
大学看了89的记录片，算是所谓的禁片。完全支持政府当时的决策，这个世界总会有人为自己的无知付出血的代价，与其留着祸害社会，不如斩草除根。合法，甚至仅仅只是合理的权益，就应该通过正常的途径去争取，暴力只会引来更大的暴力。建议多了解下89，坦克履带下的血水，请引以为鉴。

**Comment by NicoleTYF** [comment]
@NjinN  謝謝你的感想。我也看了89的紀錄片，完全覺得政府可以用一些更和平和更有軟實力的方案 (e.g. 在中全會或在大學舉辦公開辯論活動，給聽眾的思想自己決定哪一邊自己比較相信)。你說的89學潮我挺好奇的，我看看有沒有當年人民的紀錄片，然後跟現代的評論作比較。我也建議了解鄧小平六四之後為什麼說後悔。身為要成長的同路人，要理解好的一面，也要理解反的一面。
