### ISSUE TITLE
看你的一些描述太假了

### ISSUE THREAD

**Issue by seamounts** [taibangle/awesome-china#8]
包括新疆那些事，请你自己来新疆看看实际的情况吧。不要用的假的离谱的东西来攻击中国。真的请你来看看，如果你自己真的了解了你就不会这么说了。

**Comment by NicoleTYF** [comment]
I really invite you to come to Hong Kong to see for yourself, if you really understand you won't said his documentary is fake. 

I think the creator's intention is to exchange knowledge, not triggering you to debate. If realness is your concern, you can choose to watch historical documentaries made in 1989.
https://www.youtube.com/watch?v=QB9s5kSVj4Q

**Comment by seamounts** [comment]
@MeiWithHongKong 这就是你的自由？我说了一些我的意见你就把我打上 五毛 的标签？你如果对我说的不赞同，那你可以说出你的观点啊和证据啊！！

**Comment by seamounts** [comment]
> I really invite you to come to Hong Kong to see for yourself, if you really understand you won't said his documentary is fake.
> 
> I think the creator's intention is to exchange knowledge, not triggering you to debate. If realness is your concern, you can choose to watch historical documentaries made in 1989.
> https://www.youtube.com/watch?v=QB9s5kSVj4Q

我赞同你说的部分内容，也愿意交换意见。但是我厌恶的是用假新闻假证据来诬陷的做法。现在好多新闻媒体都有自己的政治立场（包括苹果日报）

**Comment by NicoleTYF** [comment]
I met friends from ShanDong, BeiJing and GuangZhou who are also traumatized by this since they saw it quite frequently in Chinese media? 
I feel really sorry for your experience in mainland China, but please don't use your emotion to attack him because of your experience, he doesn't deserve that either.

My mainland friends and I currently in Australia are working out ways to merge this picture together, and we find that in mainland they avoid talking about politics and thus has a taboo feeling on lots of things that are political. I have to explain the whole Hong Kong legal process, how Freedom of Speech is build based on Rule of Law(which therefore makes responsibility equal every right), the difference between Rule of Law in HK and Rule by Man in mainland and how to relate all the above things to Chinese's daily lives just to prevent the labels of 废青 and other hate speech I see on Hong Kong people.

For Hong Kong people's opinion I suggest you to see 
2019香港示威浪潮的第五輪民意調查結果http://video3.mingpao.com/inews/201910/20191015_mpsurvey.pdf
The reason why I recommend this is because
1. 《明報》from my 6 years of reading it, is a relatively neutral newspaper, they will just report what they see without adding too much adjectives. 
2. 香港中文大學 傳播與民意調查中心 has 22 years of surveying experiences done by local university professors, if you want to see how they do the survey take a look at p.2 of the document. My teachers in school also use data from this institution as a teaching material.
3. When this poll is out, it is also referenced by both pro-democracy and pro-China medias, though they referenced and talked about their side.

Regarding to 好多新闻媒体都有自己的政治立场, the thing is you are not forced to see their news. The people of Hong Kong live in an environment with diverse opinions and ways of expression for years and I can tell you I find this diverse environment light up my life in unexpected ways. 
Anyway, how we cope with some news channel we don't want to see, is to simply train some self-discipline to yourself to not click on the clickbaits. If you see that on Facebook, click the "..." button at the top-right corner of the post, and select "I don't want to see this", then click "unfollow (the post-er you don't want to see)".

**Comment by MeiWithHongKong** [comment]
The purpose of the repo is not to spread lies and misinformation, or to insult the Chinese people. Most of the content is taken from Wikipedia, which is arguable the most reputable and least biased source you can find, as all the content in the article has to be sourced (with sources that can be verified or have high credibility). I could've posted articles that paint CCP in a much worse light, but I didn't, because I only want to share truthful information.

If you come here to post lies, misinformation, whataboutism or death threats, then don’t expect a serious discussion. If you believe the content contain false information, or wish to discuss what’s happening in Xinjiang, Hong Kong, Tibet, etc. then you’re welcome to do so, but please act in good faith.

To say that the Chinese people are taught about the negative parts of the CCP’s history is a lie. Sure, Chinese people will know the Cultural Revolution happened, but the schools won’t go into details about the negative parts (and will lie about things such as estimated number of deaths), and it’s near impossible for the average Chinese person to find truthful information about these things due to the GFW, which is why the Wikipedia articles has been mirrored to this repo.
Today people still don’t dare to discuss the Tiananmen Square Massacre, and they're even [afraid to acknowledge that the incident happened](https://vimeo.com/44078865).

As for Xinjiang, first the government lied about the Uyghurs being taken away, said that the camps didn’t exist. When the evidence became irrefutable they later admitted that the camps did in fact exist and that they’re for “re-education”. Why would they initially lie? Why do they not allow press to enter the region? Why are those who enter not allowed to talk to the locals? Look at the video of the [VICE reporters who went undercover](https://www.youtube.com/watch?v=v7AYyUqrMuQ). You can see cameras and police everywhere. You can see that they’re not allowed to talk to locals. You can see that they’re forced to show the police their phone, and delete the pictures and videos they take. How can you trust anything the government says about Xinjiang when you have evidence that they do these things?

**Comment by wysnxzm** [comment]
通篇就是我没去过但是别人说的都是真的,笑死了

**Comment by MeiWithHongKong** [comment]
This is what it's like to have a discussion with wumaos. They ignore whatever you say and just sprout nonsense.

I have been Xinjiang, but I went there before the CCP started putting innocent people in concentration camps for crimes that include having WhatsApp installed on their phone, having family living abroad and whatnot. When I went there they didn't have surveillance cameras and police everywhere, and people were living peacefully. All the Uyghurs I met gave me a good impression, and I didn't encounter a single negative incident during my trip. The young Uyghurs I met could speak Mandarin, some of them could even speak English.

Xinjiang has obviously changed a lot during the past few years, and you don't need to go there yourself in order to learn about these things, because despite CCP's best efforts to isolate the region from the rest of the world, then there has been countless leaks from prisoners who managed to escape the country, friends and loved ones who managed to keep contact with those living there, reporters who went undercover, etc.
Whether you believe the hundreds of interviews with former prisoners who all share similar stories of rape, torture and human experiments is up to you. Most crimes don't have irrefutable evidence, instead they rely on the likes of witness testimonies. Also keep in mind that the victims who speak up and share their story have nothing to gain.. in fact, they risk the lives of their family and loved ones by doing so.
It is, however, absolutely baffling that you can see the video of VICE reporters ([GitHub link](https://raw.githubusercontent.com/taibangle/awesome-china-media/master/xinjiang/videos/chinas-vanishing-muslims.mp4)/[YouTube link](https://www.youtube.com/watch?v=v7AYyUqrMuQ) and think that what's happening there is normal or in any way justified. You also have to keep in mind that these people are risking their lives to try to uncover what's happening by seeking out the camps, collecting video evidence and talking to locals. Would you dare to do the same?

Your argument is equivalent to saying the Nanjing Massacre didn't happen because you didn't witness it with your own eyes. You really think this is a good argument?

**Comment by JeryLi** [comment]
我只能说文革是真，六十四是真，执政党那时候是犯了错误，这必须得承认，但是能不能别像小孩子，老是抓着不放，把这些作为憎恨国家和政府、仇视你们口中的大陆人的理由，我们可以Cross The GFW，来浏览很多东西，知道很多东西也是无可奈何，人口最多的国家，一旦乱？想想中东的叙利亚？近的有智利。如果想改善状况，就去参选，去做事情改善，而不是一味地指责。不过我知道你们不会，就只会上街，打砸，闹大，香港的民生是不够好，旧账怪“新主”，港英政府的烂摊子始终是要收拾好的，但能否给多点时间？其实我多少也有点理解你们，薪资低，但消费高，对未来看不到希望，但请不要怪国家和政府，还小？以为还是小孩子，闹一下就有糖吃。不去为自己的努力，反而怪环境，荒天下之大谬！唉，真的，我打这么多都不止五毛了，ridiculous，说点话就是五毛了？那旧真是永远叫不醒一个装睡的人。

**Comment by NicoleTYF** [comment]
我只能说你們現在在這裏不喜歡我們的是真，你們的民族仇恨是真，执政党那时候是犯了错误，这不但要承认還必须得從中進步 (e.g. 鄧小平11人大六四決定的『改革開放』和廢除主席終身制， 被19人大習近平在2018年推翻了)，但是你們能不能别像小孩子，老是抓着"抓着国家和政府事實的人"不放，把这些作为憎恨弱小小數的人、仇视你们口中的香港人的理由 (e.g. 抓着這個帖子不放的人)，你们要Cross The GFW，才能来浏览很多东西，才知道你們的處境也是无可奈何 (你看 NordVPN 賣的那麼火就无可奈何)。
人口最多的国家，一旦沒了一黨專政？想想沒有法西斯的法國？近的有委内瑞拉的50%人民反獨裁政府。如果想改善状况，香港現在就有歷史創20年來新高的人數去参选和選票十一月的區議會，去對做長年政府建制派多年不理民生的事情改善（e.g. 九龍東選人的政綱說移除九成市民反對的九龍的音樂小白象工程），而不能像你們一味地怕『爺爺』的 (話說把國家人性化降做人爹媽爺娘，又罵自己中國人狗，用這些詞的人平時也不是尊重別人)。
不过我知道你们不会，就只会說自己愛國又不承傳華夏的仁義礼智信 (e.g. 「美分」「綠綠」的標籤)，又對不是中國出產的東西陰謀論 (e.g. 英國39越南人蛇慘案)，把普通的廣告闹大成辱華 (e.g. Tiffany & Co. 的廣告)，大陸的民生和治安是不够好，旧账怪罪中華民國 (e.g. 清朝湖北鐵路債卷的國債)，你們在這裏罵人的烂摊子始终是要留給別人收拾好的。
其实我多少也有点理解你们，都是知道一黨專政，但缺少政治參與性，少公民義務概念 (e.g. 政黨和國家是兩個不同概念)，看到你們資訊不對等而產生的仇恨，我們當然对未来看不到希望，但请不要怪社會棟樑，还小？以为有你沒有聽過的聲音的人都是小孩子，闹一下我們共產黨就會當你貴人。不去为自己的努力改變**現在習近平修憲終身制**和**自己國因在WTO從2001年違約欠下的國債**，反而怪別人『無知』，荒天下之大谬！唉，真的，我舉这么多例子都不止『[废青nmsl ](https://github.com/taibangle/awesome-china/issues/4)』了，ridiculous，说点话就是废青了？那旧真是永远叫不醒一个装睡的人。

你好像來這裏就只是想反駁，也不是交流，看看如果我把這個話調轉來就明白我的感受吧？
『大陸』是廣州方言口語化『內地』的意思，是「大的陸地」，其實是文化差異的誤會。
你們這樣情緒化的駁下去會令我們兩的心情不會好過，也導致兩敗俱傷。
